# Generated by Django 5.0.3 on 2024-04-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilder', '0002_bild_name_alter_bild_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bild',
            name='name',
        ),
        migrations.AlterField(
            model_name='bild',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bild',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
    ]
