# Generated by Django 5.0.3 on 2024-04-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilder', '0004_bild_name_alter_bild_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bild',
            name='image_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='bild',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
